AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false